name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-on-linux:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: build with GCC in c++11
            run: |
                autoreconf -i
                CXX="g++ -std=c++11" ./configure
                make -j$(nproc)
                make clean
                find . -iname .deps | xargs rm -rf
        -   name: build with Clang in c++11
            run: |
                autoreconf -i
                CXX="clang++ -std=c++11" ./configure
                make -j$(nproc)
                make clean
                find . -iname .deps | xargs rm -rf
    build-on-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: cmd
        steps:
        -   uses: actions/checkout@v4
        -   name: setup msbuild
            uses: microsoft/setup-msbuild@v1.1
            with:
                msbuild-architecture: x64
        -   name: build
            run: MSBuild "TMChat.sln" "-t:Build" "-p:Configuration=Release;Platform=x64"
        -   name: clean
            run: MSBuild "TMChat.sln" "-t:Clean" "-p:Configuration=Release;Platform=x64"
